language: python
python: 2.7
sudo: false

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34

install:
  - pip install -r requirements.txt

script:
  - tox -e $TOX_ENV

after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/stardust85/repositorytools $GIT_TAG > /dev/null 2>&1

branches:
  except:
    - /^build-[0-9a-z\-]*/
